dist: focal

language: node_js

node_js:
    - 20.10.0

cache:
    npm: false
    directories:
        - ~/.pnpm-store

before_install:
    - npm add -g pnpm
    - pnpm config set store-dir ~/.pnpm-store

install:
    - pnpm i
    - pnpm build

script:
    - pnpm ci
