services:
    nginx:
        image: nginx:1.27.3-alpine
        restart: always
        ports:
            - ${WEBSITE_PORT}:6700
        volumes:
            - ../nginx:/etc/nginx/templates
    web:
        build:
            context: ../..
            dockerfile: configs/docker/Dockerfile
            target: web
            args:
                NODE_IMAGE: node:22.11.0-alpine
                PUBLIC_TITLE: ${PUBLIC_TITLE}
                PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
        restart: always
    api:
        build:
            context: ../..
            dockerfile: configs/docker/Dockerfile
            target: api
            args:
                NODE_IMAGE: node:22.11.0-alpine
        restart: always
        environment:
            PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
            POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
            MINIO_USER: ${MINIO_USER}
            MINIO_PASSWORD: ${MINIO_PASSWORD}
            JWT_SECRET: ${JWT_SECRET}
            TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
            TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
            MAILER_HOST: ${MAILER_HOST}
            MAILER_PORT: ${MAILER_PORT}
            MAILER_EMAIL: ${MAILER_EMAIL}
            MAILER_PASSWORD: ${MAILER_PASSWORD}
            MAILER_NAME: ${MAILER_NAME}
            ENABLE_DOCS: ${ENABLE_DOCS}
    postgres:
        image: postgres:17.2-alpine
        restart: always
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres:/var/lib/postgresql/data
    minio:
        image: minio/minio:RELEASE.2024-12-18T13-15-44Z
        restart: always
        ports:
            - ${MINIO_PORT}:9000
        environment:
            MINIO_ROOT_USER: ${MINIO_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
        volumes:
            - minio:/data
            - ../../storage/minio-tmp:/backup
        command: server /data --console-address :9001
    alpine:
        image: alpine:3.21.2
        restart: always
        tty: true
        volumes:
            - ../../storage:/storage
