services:
    nginx:
        image: nginx:1.27.5-alpine
        restart: always
        ports:
            - ${WEBSITE_PORT}:6700
        volumes:
            - ../nginx:/etc/nginx/templates
    web:
        build:
            context: ../..
            dockerfile: configs/docker/Dockerfile
            target: web
            args:
                NODE_IMAGE: node:22.14.0-alpine
                PUBLIC_TITLE: ${PUBLIC_TITLE}
                PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
        restart: always
    api:
        build:
            context: ../..
            dockerfile: configs/docker/Dockerfile
            target: api
            args:
                NODE_IMAGE: node:22.14.0-alpine
        restart: always
        environment:
            PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
            POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
            MINIO_USER: ${MINIO_USER}
            MINIO_PASSWORD: ${MINIO_PASSWORD}
            JWT_SECRET: ${JWT_SECRET}
            TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
            TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
            MAILER_HOST: ${MAILER_HOST}
            MAILER_PORT: ${MAILER_PORT}
            MAILER_EMAIL: ${MAILER_EMAIL}
            MAILER_PASSWORD: ${MAILER_PASSWORD}
            MAILER_NAME: ${MAILER_NAME}
            ENABLE_DOCS: ${ENABLE_DOCS}
    postgres:
        image: postgres:17.4-alpine
        restart: always
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres:/var/lib/postgresql/data
    adminer:
        image: adminer:5.2.1
        restart: always
    minio:
        image: minio/minio:RELEASE.2025-04-08T15-41-24Z
        restart: always
        environment:
            MINIO_ROOT_USER: ${MINIO_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
        volumes:
            - minio:/data
            - ../../storage/minio-tmp:/backup
            - ../minio:/minio
        command: server /data --console-address :9001
    alpine:
        image: alpine:3.21.3
        restart: always
        tty: true
        volumes:
            - ../../storage:/storage
