services:
    nginx:
        image: nginx:1.23.2-alpine
        restart: always
        ports:
            - ${WEBSITE_PORT}:6700
        volumes:
            - ../nginx:/etc/nginx/templates
    web:
        build:
            context: ../../services/web
            args:
                NODE_IMAGE: node:18.1.0-alpine
        restart: always
    api:
        build:
            context: ../../services/api
            args:
                NODE_IMAGE: node:18.1.0-alpine
        restart: always
