services:
    nginx:
        image: nginx:1.21.1-alpine
        restart: always
        environment:
            WEBSITE_PORT: ${WEBSITE_PORT}
        volumes:
            - ../nginx:/etc/nginx/templates
    web:
        build:
            context: ../../services/web
            args:
                NODE_IMAGE: node:16.8.0-alpine
        restart: always
