services:
    nginx:
        image: nginx:1.23.3-alpine
        restart: always
        ports:
            - ${WEBSITE_PORT}:6700
        volumes:
            - ../nginx:/etc/nginx/templates
    web:
        build:
            context: ../../services/web
            args:
                NODE_IMAGE: node:18.14.0-alpine
                PUBLIC_TITLE: ${PUBLIC_TITLE}
                PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
        restart: always
    api:
        build:
            context: ../../services/api
            args:
                NODE_IMAGE: node:18.14.0-alpine
        restart: always
        environment:
            POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
            JWT_SECRET: ${JWT_SECRET}
            MAILER_HOST: ${MAILER_HOST}
            MAILER_PORT: ${MAILER_PORT}
            MAILER_EMAIL: ${MAILER_EMAIL}
            MAILER_PASSWORD: ${MAILER_PASSWORD}
            MAILER_NAME: ${MAILER_NAME}
            EMAIL_CONFIRMATION_URL: ${EMAIL_CONFIRMATION_URL}
            PASSWORD_RESET_URL: ${PASSWORD_RESET_URL}
            ENABLE_DOCS: ${ENABLE_DOCS}
        volumes:
            - ../../storage/files:/app/files
    postgres:
        image: postgres:15.1-alpine
        restart: always
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ../../storage/postgres:/var/lib/postgresql/data
