volumes:
    postgres:
        name: ${VOLUME_PREFIX}_postgres
    minio:
        name: ${VOLUME_PREFIX}_minio

services:
    nginx:
        extends:
            file: ./base.yml
            service: nginx
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            WEB_HOST: host.docker.internal
            API_HOST: host.docker.internal
            MINIO_HOST: host.docker.internal
            MINIO_PORT: ${MINIO_DEV_PORT}
            MINIO_CONSOLE_PORT: ${MINIO_DEV_CONSOLE_PORT}
    postgres:
        extends:
            file: ./base.yml
            service: postgres
    minio:
        extends:
            file: ./base.yml
            service: minio
        ports:
            - ${MINIO_DEV_PORT}:9000
            - ${MINIO_DEV_CONSOLE_PORT}:9001
    alpine:
        extends:
            file: ./base.yml
            service: alpine
