services:
    nginx:
        extends:
            file: ./base.yml
            service: nginx
        network_mode: host
        environment:
            WEB_HOST: localhost
            API_HOST: localhost
    postgres:
        extends:
            file: ./base.yml
            service: postgres
