services:
    nginx:
        extends:
            file: ./base.yml
            service: nginx
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            WEB_HOST: host.docker.internal
            API_HOST: host.docker.internal
    postgres:
        extends:
            file: ./base.yml
            service: postgres
