services:
    nginx:
        extends:
            file: ./base.yml
            service: nginx
        network_mode: host
        environment:
            WEB_CLIENT_HOST: localhost
            API_HOST: localhost
    mongo:
        extends:
            file: ./base.yml
            service: mongo
