volumes:
    postgres:
        name: ${VOLUME_PREFIX}_postgres
    minio:
        name: ${VOLUME_PREFIX}_minio

services:
    nginx:
        extends:
            file: ./base.yml
            service: nginx
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            WEB_HOST: host.docker.internal
            API_HOST: host.docker.internal
            MINIO_HOST: host.docker.internal
    postgres:
        extends:
            file: ./base.yml
            service: postgres
        ports:
            - 6703:5432
    adminer:
        extends:
            file: ./base.yml
            service: adminer
        depends_on:
            - postgres
    minio:
        extends:
            file: ./base.yml
            service: minio
        ports:
            - 6704:9000
    alpine:
        extends:
            file: ./base.yml
            service: alpine
