services:
    nginx:
        extends:
            file: ./base.yml
            service: nginx
        ports:
            - ${WEBSITE_PORT}:${WEBSITE_PORT}
        environment:
            WEB_HOST: web
            API_HOST: api
        depends_on:
            - web
    web:
        extends:
            file: ./base.yml
            service: web
        depends_on:
            - api
    api:
        extends:
            file: ./base.yml
            service: api
        depends_on:
            - postgres
    postgres:
        extends:
            file: ./base.yml
            service: postgres
    pgbackups:
        extends:
            file: ./base.yml
            service: pgbackups
        depends_on:
            - postgres
