volumes:
    postgres:
        name: ${VOLUME_PREFIX}_postgres
    minio:
        name: ${VOLUME_PREFIX}_minio

services:
    nginx:
        extends:
            file: ./base.yml
            service: nginx
        environment:
            WEB_HOST: web
            API_HOST: api
            MINIO_HOST: minio
        depends_on:
            - web
    web:
        extends:
            file: ./base.yml
            service: web
        depends_on:
            - api
    api:
        extends:
            file: ./base.yml
            service: api
        depends_on:
            - postgres
            - minio
    postgres:
        extends:
            file: ./base.yml
            service: postgres
    minio:
        extends:
            file: ./base.yml
            service: minio
    alpine:
        extends:
            file: ./base.yml
            service: alpine
