services:
    nginx:
        extends:
            file: ./base.yml
            service: nginx
        ports:
            - ${WEBSITE_PORT}:${WEBSITE_PORT}
        environment:
            WEB_HOST: web
        depends_on:
            - web
    web:
        extends:
            file: ./base.yml
            service: web
