services:
    nginx:
        extends:
            file: ./base.yml
            service: nginx
        environment:
            WEB_HOST: web
            API_HOST: api
        depends_on:
            - web
    web:
        extends:
            file: ./base.yml
            service: web
        depends_on:
            - api
    api:
        extends:
            file: ./base.yml
            service: api
