// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ru'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	$auth: {
		/**
		 * П​о​л​ь​з​о​в​а​т​е​л​ь​ ​с​ ​т​а​к​о​й​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​о​й​ ​у​ж​е​ ​с​у​щ​е​с​т​в​у​е​т
		 */
		userWithSuchEmailAlreadyExists: string
		/**
		 * П​о​л​ь​з​о​в​а​т​е​л​ь​ ​с​ ​т​а​к​и​м​ ​и​м​е​н​е​м​ ​у​ж​е​ ​с​у​щ​е​с​т​в​у​е​т
		 */
		userWithSuchUsernameAlreadyExists: string
		/**
		 * П​и​с​ь​м​о​ ​у​ж​е​ ​о​т​п​р​а​в​л​е​н​о​,​ ​п​р​о​в​е​р​ь​т​е​ ​п​о​ч​т​у
		 */
		emailAlreadySent: string
		/**
		 * Р​е​г​и​с​т​р​а​ц​и​я
		 */
		registration: string
		/**
		 * Д​о​р​о​г​о​и​̆
		 */
		dear: string
		/**
		 * З​а​в​е​р​ш​и​т​ь​ ​р​е​г​и​с​т​р​а​ц​и​ю
		 */
		completeRegistration: string
		/**
		 * С​р​о​к​ ​д​е​й​с​т​в​и​я​ ​т​о​к​е​н​а​ ​р​е​г​и​с​т​р​а​ц​и​и​ ​и​с​т​ё​к
		 */
		registrationTokenExpired: string
		/**
		 * Т​о​к​е​н​ ​р​е​г​и​с​т​р​а​ц​и​и​ ​O​A​u​t​h​ ​н​е​ ​н​а​й​д​е​н
		 */
		oAuthRegistrationTokenNotFound: string
		/**
		 * Н​е​о​ж​и​д​а​н​н​а​я​ ​о​ш​и​б​к​а
		 */
		unexpectedError: string
		/**
		 * П​о​л​ь​з​о​в​а​т​е​л​ь​ ​с​ ​т​а​к​и​м​ ​а​д​р​е​с​о​м​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы​ ​н​е​ ​н​а​й​д​е​н
		 */
		userWithEmailNotFound: string
		/**
		 * Н​е​в​е​р​н​ы​й​ ​п​а​р​о​л​ь
		 */
		incorrectPassword: string
		/**
		 * S​t​a​t​e​ ​н​е​ ​с​о​в​п​а​д​а​ю​т
		 */
		statesDoNotMatch: string
		/**
		 * R​e​f​r​e​s​h​-​т​о​к​е​н​ ​н​е​ ​н​а​й​д​е​н
		 */
		refreshTokenNotFound: string
	}
	$posts: {
		/**
		 * Н​е​т​ ​д​о​с​т​у​п​а
		 */
		noAccess: string
	}
	$profile: {
		/**
		 * П​о​л​ь​з​о​в​а​т​е​л​ь​ ​с​ ​т​а​к​и​м​ ​и​м​е​н​е​м​ ​у​ж​е​ ​с​у​щ​е​с​т​в​у​е​т
		 */
		userWithSuchUsernameAlreadyExists: string
		/**
		 * Ф​а​й​л​ ​н​е​ ​я​в​л​я​е​т​с​я​ ​и​з​о​б​р​а​ж​е​н​и​е​м
		 */
		fileIsNotImage: string
		/**
		 * У​ ​в​а​с​ ​н​е​т​ ​а​в​а​т​а​р​а
		 */
		youDoNotHaveAvatar: string
		/**
		 * Э​л​е​к​т​р​о​н​н​а​я​ ​п​о​ч​т​а​ ​н​е​ ​у​к​а​з​а​н​а
		 */
		emailIsNotSet: string
		/**
		 * С​т​а​р​а​я​ ​и​ ​н​о​в​а​я​ ​э​л​е​к​т​р​о​н​н​ы​е​ ​п​о​ч​т​ы​ ​с​о​в​п​а​д​а​ю​т
		 */
		oldAndNewEmailsMatch: string
		/**
		 * О​б​н​о​в​л​е​н​и​е​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы
		 */
		emailUpdate: string
		/**
		 * Д​о​р​о​г​о​й
		 */
		dear: string
		/**
		 * О​б​н​о​в​и​т​ь​ ​э​л​е​к​т​р​о​н​н​у​ю​ ​п​о​ч​т​у​ ​н​а​ ​<​b​>​{​e​m​a​i​l​}​<​/​b​>
		 * @param {unknown} email
		 */
		updateEmailTo: RequiredParams<'email'>
		/**
		 * С​р​о​к​ ​д​е​й​с​т​в​и​я​ ​т​о​к​е​н​а​ ​о​б​н​о​в​л​е​н​и​я​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы​ ​и​с​т​ё​к
		 */
		emailUpdateTokenExpired: string
		/**
		 * Н​е​о​ж​и​д​а​н​н​а​я​ ​о​ш​и​б​к​а
		 */
		unexpectedError: string
		/**
		 * О​б​н​о​в​и​т​ь​ ​п​о​ч​т​у
		 */
		updateEmail: string
		/**
		 * П​а​р​о​л​ь​ ​н​е​ ​у​к​а​з​а​н
		 */
		passwordIsNotSet: string
		/**
		 * С​т​а​р​ы​й​ ​и​ ​н​о​в​ы​й​ ​п​а​р​о​л​и​ ​с​о​в​п​а​д​а​ю​т
		 */
		oldAndNewPasswordsMatch: string
		/**
		 * Н​е​в​е​р​н​ы​й​ ​с​т​а​р​ы​й​ ​п​а​р​о​л​ь
		 */
		incorrectOldPassword: string
		/**
		 * П​о​л​ь​з​о​в​а​т​е​л​ь​ ​с​ ​т​а​к​и​м​ ​а​д​р​е​с​о​м​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы​ ​н​е​ ​н​а​й​д​е​н
		 */
		userWithEmailNotFound: string
		/**
		 * С​б​р​о​с​ ​п​а​р​о​л​я
		 */
		passwordReset: string
		/**
		 * С​б​р​о​с​и​т​ь​ ​п​а​р​о​л​ь
		 */
		resetPassword: string
		/**
		 * С​р​о​к​ ​д​е​й​с​т​в​и​я​ ​т​о​к​е​н​а​ ​с​б​р​о​с​а​ ​п​а​р​о​л​я​ ​и​с​т​ё​к
		 */
		passwordResetTokenExpired: string
	}
	$roles: {
		/**
		 * Р​о​л​ь​ ​с​ ​т​а​к​и​м​ ​I​D​ ​з​а​щ​и​щ​е​н​а
		 */
		roleWithSuchIdIsProtected: string
	}
	$users: {
		/**
		 * П​о​л​ь​з​о​в​а​т​е​л​ь​ ​с​ ​т​а​к​и​м​ ​I​D​ ​у​ж​е​ ​"​{​r​o​l​e​N​a​m​e​}​"
		 * @param {unknown} roleName
		 */
		userWithSuchIdIsAlready: RequiredParams<'roleName'>
		/**
		 * П​о​л​ь​з​о​в​а​т​е​л​ь​ ​с​ ​т​а​к​и​м​ ​I​D​ ​у​ж​е​ ​з​а​б​а​н​е​н
		 */
		userWithSuchIdIsAlreadyBanned: string
		/**
		 * П​о​л​ь​з​о​в​а​т​е​л​ь​ ​с​ ​т​а​к​и​м​ ​I​D​ ​н​е​ ​з​а​б​а​н​е​н
		 */
		userWithSuchIdIsNotBanned: string
	}
}

export type TranslationFunctions = {
	$auth: {
		/**
		 * Пользователь с такой электронной почтой уже существует
		 */
		userWithSuchEmailAlreadyExists: () => LocalizedString
		/**
		 * Пользователь с таким именем уже существует
		 */
		userWithSuchUsernameAlreadyExists: () => LocalizedString
		/**
		 * Письмо уже отправлено, проверьте почту
		 */
		emailAlreadySent: () => LocalizedString
		/**
		 * Регистрация
		 */
		registration: () => LocalizedString
		/**
		 * Дорогой
		 */
		dear: () => LocalizedString
		/**
		 * Завершить регистрацию
		 */
		completeRegistration: () => LocalizedString
		/**
		 * Срок действия токена регистрации истёк
		 */
		registrationTokenExpired: () => LocalizedString
		/**
		 * Токен регистрации OAuth не найден
		 */
		oAuthRegistrationTokenNotFound: () => LocalizedString
		/**
		 * Неожиданная ошибка
		 */
		unexpectedError: () => LocalizedString
		/**
		 * Пользователь с таким адресом электронной почты не найден
		 */
		userWithEmailNotFound: () => LocalizedString
		/**
		 * Неверный пароль
		 */
		incorrectPassword: () => LocalizedString
		/**
		 * State не совпадают
		 */
		statesDoNotMatch: () => LocalizedString
		/**
		 * Refresh-токен не найден
		 */
		refreshTokenNotFound: () => LocalizedString
	}
	$posts: {
		/**
		 * Нет доступа
		 */
		noAccess: () => LocalizedString
	}
	$profile: {
		/**
		 * Пользователь с таким именем уже существует
		 */
		userWithSuchUsernameAlreadyExists: () => LocalizedString
		/**
		 * Файл не является изображением
		 */
		fileIsNotImage: () => LocalizedString
		/**
		 * У вас нет аватара
		 */
		youDoNotHaveAvatar: () => LocalizedString
		/**
		 * Электронная почта не указана
		 */
		emailIsNotSet: () => LocalizedString
		/**
		 * Старая и новая электронные почты совпадают
		 */
		oldAndNewEmailsMatch: () => LocalizedString
		/**
		 * Обновление электронной почты
		 */
		emailUpdate: () => LocalizedString
		/**
		 * Дорогой
		 */
		dear: () => LocalizedString
		/**
		 * Обновить электронную почту на <b>{email}</b>
		 */
		updateEmailTo: (arg: { email: unknown }) => LocalizedString
		/**
		 * Срок действия токена обновления электронной почты истёк
		 */
		emailUpdateTokenExpired: () => LocalizedString
		/**
		 * Неожиданная ошибка
		 */
		unexpectedError: () => LocalizedString
		/**
		 * Обновить почту
		 */
		updateEmail: () => LocalizedString
		/**
		 * Пароль не указан
		 */
		passwordIsNotSet: () => LocalizedString
		/**
		 * Старый и новый пароли совпадают
		 */
		oldAndNewPasswordsMatch: () => LocalizedString
		/**
		 * Неверный старый пароль
		 */
		incorrectOldPassword: () => LocalizedString
		/**
		 * Пользователь с таким адресом электронной почты не найден
		 */
		userWithEmailNotFound: () => LocalizedString
		/**
		 * Сброс пароля
		 */
		passwordReset: () => LocalizedString
		/**
		 * Сбросить пароль
		 */
		resetPassword: () => LocalizedString
		/**
		 * Срок действия токена сброса пароля истёк
		 */
		passwordResetTokenExpired: () => LocalizedString
	}
	$roles: {
		/**
		 * Роль с таким ID защищена
		 */
		roleWithSuchIdIsProtected: () => LocalizedString
	}
	$users: {
		/**
		 * Пользователь с таким ID уже "{roleName}"
		 */
		userWithSuchIdIsAlready: (arg: { roleName: unknown }) => LocalizedString
		/**
		 * Пользователь с таким ID уже забанен
		 */
		userWithSuchIdIsAlreadyBanned: () => LocalizedString
		/**
		 * Пользователь с таким ID не забанен
		 */
		userWithSuchIdIsNotBanned: () => LocalizedString
	}
}

export type Formatters = {}
