#!/usr/bin/env sh

SCRIPTS_DIR=$(dirname "$0")
ROOT_DIR=$SCRIPTS_DIR/..

if ! [ -f "$ROOT_DIR"/.env ]
then
    cp "$ROOT_DIR"/.env.example "$ROOT_DIR"/.env
    echo "The .env file has been created successfully"
fi

exit 0
