#!/usr/bin/env sh

SCRIPTS_DIR=$(dirname "$0")
ROOT_DIR=$SCRIPTS_DIR/..
STORAGE_DIR=$ROOT_DIR/storage
MINIO_TMP_DIR=$STORAGE_DIR/minio-tmp

ABS_BACKUP_DIR=$(realpath "$STORAGE_DIR"/backups)/$(date -u +'%Y-%m-%d_%H-%M-%S')

if [ -n "$(scripts/dev ps -q)" ]; then
    MODE="dev"
elif [ -n "$(scripts/prod ps -q)" ]; then
    MODE="prod"
else
    echo "Containers are not running"
    exit 1
fi

. "$ROOT_DIR"/.env

sudo echo Requesting sudo password > /dev/null

mkdir -p "$ABS_BACKUP_DIR"/files

rm -rf "$MINIO_TMP_DIR"/*

scripts/"$MODE" exec minio mc alias set local http://minio:9000 "$MINIO_USER" "$MINIO_PASSWORD" > /dev/null
scripts/"$MODE" exec minio mc mirror local/files /backup > /dev/null

scripts/"$MODE" exec alpine chown -R "$(id -u)":"$(id -g)" /storage/minio-tmp
scripts/"$MODE" exec alpine chmod -R 644 /storage/minio-tmp
scripts/"$MODE" exec alpine find /storage/minio-tmp -type d -exec chmod 755 {} \;

cp -r "$MINIO_TMP_DIR"/* "$ABS_BACKUP_DIR"/files

scripts/"$MODE" exec postgres pg_dump -U "$POSTGRES_USER" "$POSTGRES_DB" | tee "$ABS_BACKUP_DIR"/db.sql > /dev/null

tar -zcvf "$ABS_BACKUP_DIR".tar.gz -C "$ABS_BACKUP_DIR" . > /dev/null

rm -rf "$ABS_BACKUP_DIR"

exit 0
