#!/usr/bin/env sh

set -e

SCRIPTS_DIR=$(dirname "$0")

"$SCRIPTS_DIR"/check-docker

if [ -n "$("$SCRIPTS_DIR"/run prod ps -q)" ]; then
    echo "Production containers are already running. Stop them before starting development environment"

    exit 1
fi

"$SCRIPTS_DIR"/run dev "$@"

exit 0
