#!/usr/bin/env sh

SCRIPTS_DIR=$(dirname "$0")
ROOT_DIR=$SCRIPTS_DIR/..
PGBACKUPS_DIR=$ROOT_DIR/volumes/pgbackups

. "$ROOT_DIR"/.env

"$SCRIPTS_DIR"/dev up -d postgres
"$SCRIPTS_DIR"/dev down
"$SCRIPTS_DIR"/dev up -d postgres
"$SCRIPTS_DIR"/dev exec postgres dropdb -U "$POSTGRES_USER" -f --if-exists "$POSTGRES_DB"
"$SCRIPTS_DIR"/dev exec postgres createdb -U "$POSTGRES_USER" "$POSTGRES_DB"
zcat "$PGBACKUPS_DIR"/"$1" | "$SCRIPTS_DIR"/dev exec -T postgres psql -U "$POSTGRES_USER" -d "$POSTGRES_DB"
"$SCRIPTS_DIR"/dev down

exit 0
