#!/usr/bin/env sh

SCRIPTS_DIR=$(dirname "$0")

if [ -n "$("$SCRIPTS_DIR"/run dev ps -q)" ]; then
    echo "Development containers are already running. Stop them before starting production environment"

    exit 1
fi

"$SCRIPTS_DIR"/run prod "$@"

exit 0
