#!/usr/bin/env sh

SCRIPTS_DIR=$(dirname "$0")
ROOT_DIR=$SCRIPTS_DIR/..
STORAGE_DIR=$ROOT_DIR/storage
BACKUPS_DIR=$STORAGE_DIR/backups

ABS_ROOT_DIR=$(realpath "$ROOT_DIR")

if [ "$(scripts/dev ps -q && scripts/prod ps -q)" ]
then
    echo Please stop containers before doing this
else
    cd "$STORAGE_DIR" || exit
    sudo rm -rf postgres files
    cd "$ABS_ROOT_DIR" || exit
    sudo tar -xvf "$BACKUPS_DIR"/"$1".tar.gz -C "$STORAGE_DIR" > /dev/null
fi

exit 0
