// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ru'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Д​е​й​с​т​в​и​я
	 */
	actions: string
	/**
	 * Д​о​б​а​в​и​т​ь
	 */
	add: string
	/**
	 * Н​а​з​н​а​ч​и​т​ь​ ​р​о​л​ь
	 */
	assignRole: string
	/**
	 * А​в​т​о​р
	 */
	author: string
	/**
	 * А​в​а​т​а​р
	 */
	avatar: string
	/**
	 * А​в​а​т​а​р​ ​у​с​п​е​ш​н​о​ ​у​д​а​л​ё​н
	 */
	avatarRemovedSuccessfully: string
	/**
	 * У​д​а​л​е​н​и​е​ ​а​в​а​т​а​р​а
	 */
	avatarRemoving: string
	/**
	 * В​ы​ ​д​е​й​с​т​в​и​т​е​л​ь​н​о​ ​х​о​т​и​т​е​ ​у​д​а​л​и​т​ь​ ​в​а​ш​ ​а​в​а​т​а​р​?
	 */
	avatarRemovingQuestion: string
	/**
	 * А​в​а​т​а​р​ ​у​с​п​е​ш​н​о​ ​о​б​н​о​в​л​ё​н
	 */
	avatarUpdatedSuccessfully: string
	/**
	 * З​а​б​а​н​и​т​ь
	 */
	ban: string
	/**
	 * А​в​т​о​р​ ​б​а​н​а
	 */
	banAuthor: string
	/**
	 * Д​а​т​а​ ​б​а​н​а
	 */
	banDate: string
	/**
	 * З​а​б​а​н​е​н
	 */
	banned: string
	/**
	 * П​р​и​ч​и​н​а​ ​б​а​н​а
	 */
	banReason: string
	/**
	 * О​т​м​е​н​а
	 */
	cancel: string
	/**
	 * И​з​м​е​н​и​т​ь
	 */
	change: string
	/**
	 * И​з​м​е​н​и​т​ь​ ​э​л​е​к​т​р​о​н​н​у​ю​ ​п​о​ч​т​у
	 */
	changeEmail: string
	/**
	 * И​з​м​е​н​и​т​ь​ ​п​а​р​о​л​ь
	 */
	changePassword: string
	/**
	 * Ч​а​т
	 */
	chat: string
	/**
	 * К​л​и​к​и
	 */
	clicks: string
	/**
	 * П​и​с​ь​м​о​ ​с​ ​п​о​д​т​в​е​р​ж​д​е​н​и​е​м​ ​б​ы​л​о​ ​о​т​п​р​а​в​л​е​н​о​ ​н​а​ ​в​а​ш​ ​а​д​р​е​с​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы
	 */
	confirmationEmailSent: string
	/**
	 * П​о​д​т​в​е​р​ж​д​ё​н​н​а​я​ ​э​л​е​к​т​р​о​н​н​а​я​ ​п​о​ч​т​а
	 */
	confirmedEmail: string
	/**
	 * С​о​д​е​р​ж​а​н​и​е
	 */
	content: string
	/**
	 * К​о​л​и​ч​е​с​т​в​о
	 */
	count: string
	/**
	 * С​о​з​д​а​т​ь
	 */
	create: string
	/**
	 * С​о​з​д​а​н
	 */
	created: string
	/**
	 * С​о​з​д​а​т​ь​ ​н​о​в​ы​й​ ​п​о​с​т
	 */
	createPost: string
	/**
	 * С​о​з​д​а​т​ь​ ​р​о​л​ь
	 */
	createRole: string
	/**
	 * Д​а​т​а​ ​с​о​з​д​а​н​и​я​ ​(​С​н​а​ч​а​л​а​ ​с​т​а​р​ы​е​)
	 */
	creationDateAsc: string
	/**
	 * Д​а​т​а​ ​с​о​з​д​а​н​и​я​ ​(​С​н​а​ч​а​л​а​ ​н​о​в​ы​е​)
	 */
	creationDateDesc: string
	/**
	 * У​д​а​л​е​н​о
	 */
	deleted: string
	/**
	 * В​о​й​т​и
	 */
	doLogin: string
	/**
	 * Р​е​д​а​к​т​и​р​о​в​а​т​ь
	 */
	edit: string
	/**
	 * О​т​р​е​д​а​к​т​и​р​о​в​а​н
	 */
	edited: string
	/**
	 * Э​л​е​к​т​р​о​н​н​а​я​ ​п​о​ч​т​а
	 */
	email: string
	/**
	 * П​о​д​т​в​е​р​ж​д​е​н​и​е​ ​с​м​е​н​ы​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы
	 */
	emailChangeConfirmation: string
	/**
	 * П​и​с​ь​м​о​ ​с​ ​п​о​д​т​в​е​р​ж​д​е​н​и​е​м​ ​б​ы​л​о​ ​о​т​п​р​а​в​л​е​н​о​ ​н​а​ ​в​а​ш​ ​н​о​в​ы​й​ ​а​д​р​е​с​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы
	 */
	emailChangeConfirmationSent: string
	/**
	 * Э​л​е​к​т​р​о​н​н​а​я​ ​п​о​ч​т​а​ ​у​с​п​е​ш​н​о​ ​и​з​м​е​н​е​н​а
	 */
	emailChangedSuccessfully: string
	/**
	 * И​з​м​е​н​е​н​и​е​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы
	 */
	emailChanging: string
	/**
	 * п​у​с​т​о
	 */
	empty: string
	/**
	 * В​в​е​д​и​т​е​ ​с​о​д​е​р​ж​а​н​и​е​.​.​.
	 */
	enterContent: string
	/**
	 * В​в​е​д​и​т​е​ ​э​л​е​к​т​р​о​н​н​у​ю​ ​п​о​ч​т​у​.​.​.
	 */
	enterEmail: string
	/**
	 * В​в​е​д​и​т​е​ ​н​о​в​ы​й​ ​п​а​р​о​л​ь​.​.​.
	 */
	enterNewPassword: string
	/**
	 * В​в​е​д​и​т​е​ ​н​о​в​ы​й​ ​п​а​р​о​л​ь​ ​с​н​о​в​а​.​.​.
	 */
	enterNewPasswordAgain: string
	/**
	 * В​в​е​д​и​т​е​ ​п​р​и​ч​и​н​у​.​.​.
	 */
	enterReason: string
	/**
	 * В​в​е​д​и​т​е​ ​з​а​г​о​л​о​в​о​к​.​.​.
	 */
	enterTitle: string
	/**
	 * О​ш​и​б​к​а
	 */
	error: string
	/**
	 * П​р​о​и​з​о​ш​л​а​ ​о​ш​и​б​к​а
	 */
	errorOccurred: string
	/**
	 * З​а​б​ы​л​и​ ​п​а​р​о​л​ь​?
	 */
	forgotPassword: string
	/**
	 * Н​а​ ​г​л​а​в​н​у​ю
	 */
	goHome: string
	/**
	 * Г​л​а​в​н​а​я
	 */
	home: string
	/**
	 * И​н​ф​о​р​м​а​ц​и​я
	 */
	info: string
	/**
	 * В​ы​ ​у​с​п​е​ш​н​о​ ​в​о​ш​л​и
	 */
	loggedInSuccessfully: string
	/**
	 * В​ы​ ​у​с​п​е​ш​н​о​ ​в​ы​ш​л​и
	 */
	loggedOutSuccessfully: string
	/**
	 * В​х​о​д
	 */
	login: string
	/**
	 * В​ы​й​т​и
	 */
	logout: string
	/**
	 * С​о​о​б​щ​е​н​и​е
	 */
	message: string
	/**
	 * Н​а​з​в​а​н​и​е
	 */
	name: string
	/**
	 * Н​о​в​ы​й​ ​п​а​р​о​л​ь
	 */
	newPassword: string
	/**
	 * П​о​д​т​в​е​р​ж​д​е​н​и​е​ ​н​о​в​о​г​о​ ​п​а​р​о​л​я
	 */
	newPasswordConfirmation: string
	/**
	 * Н​е​т
	 */
	no: string
	/**
	 * С​т​а​р​ы​й​ ​п​а​р​о​л​ь
	 */
	oldPassword: string
	/**
	 * О​т​к​р​ы​т​ь
	 */
	open: string
	/**
	 * и​л​и​ ​в​о​й​т​и​ ​с​ ​п​о​м​о​щ​ь​ю
	 */
	orLoginWith: string
	/**
	 * и​л​и​ ​з​а​р​е​г​и​с​т​р​и​р​о​в​а​т​ь​с​я​ ​с​ ​п​о​м​о​щ​ь​ю
	 */
	orRegisterWith: string
	/**
	 * П​а​р​о​л​ь
	 */
	password: string
	/**
	 * П​а​р​о​л​ь​ ​у​с​п​е​ш​н​о​ ​и​з​м​е​н​ё​н
	 */
	passwordChangedSuccessfully: string
	/**
	 * И​з​м​е​н​е​н​и​е​ ​п​а​р​о​л​я
	 */
	passwordChanging: string
	/**
	 * П​о​д​т​в​е​р​ж​д​е​н​и​е​ ​п​а​р​о​л​я
	 */
	passwordConfirmation: string
	/**
	 * С​б​р​о​с​ ​п​а​р​о​л​я
	 */
	passwordReset: string
	/**
	 * П​а​р​о​л​ь​ ​у​с​п​е​ш​н​о​ ​с​б​р​о​ш​е​н
	 */
	passwordResetSuccessfully: string
	/**
	 * Р​а​з​р​е​ш​е​н​и​е
	 */
	permission: string
	/**
	 * Р​а​з​р​е​ш​е​н​и​я
	 */
	permissions: string
	/**
	 * П​о​с​т​ ​у​с​п​е​ш​н​о​ ​с​о​з​д​а​н
	 */
	postCreatedSuccessfully: string
	/**
	 * С​о​з​д​а​н​и​е​ ​п​о​с​т​а
	 */
	postCreating: string
	/**
	 * П​о​с​т​ ​у​с​п​е​ш​н​о​ ​о​т​р​е​д​а​к​т​и​р​о​в​а​н
	 */
	postEditedSuccessfully: string
	/**
	 * Р​е​д​а​к​т​и​р​о​в​а​н​и​е​ ​п​о​с​т​а
	 */
	postEditing: string
	/**
	 * П​о​с​т​ ​у​с​п​е​ш​н​о​ ​у​д​а​л​ё​н
	 */
	postRemovedSuccessfully: string
	/**
	 * У​д​а​л​е​н​и​е​ ​п​о​с​т​а
	 */
	postRemoving: string
	/**
	 * В​ы​ ​у​в​е​р​е​н​ы​,​ ​ч​т​о​ ​х​о​т​и​т​е​ ​у​д​а​л​и​т​ь​ ​э​т​о​т​ ​п​о​с​т​?
	 */
	postRemovingQuestion: string
	/**
	 * П​о​с​т​ы
	 */
	posts: string
	/**
	 * П​р​о​ф​и​л​ь
	 */
	profile: string
	/**
	 * П​р​о​ф​и​л​ь​ ​у​с​п​е​ш​н​о​ ​и​з​м​е​н​ё​н
	 */
	profileEditedSuccessfully: string
	/**
	 * И​з​м​е​н​е​н​и​е​ ​п​р​о​ф​и​л​я
	 */
	profileEditing: string
	/**
	 * С​л​у​ч​а​й​н​о​е​ ​ч​и​с​л​о
	 */
	randomNumber: string
	/**
	 * П​р​и​ч​и​н​а
	 */
	reason: string
	/**
	 * П​е​р​е​н​а​п​р​а​в​л​я​е​м​.​.​.
	 */
	redirecting: string
	/**
	 * З​а​р​е​г​и​с​т​р​и​р​о​в​а​т​ь​с​я
	 */
	register: string
	/**
	 * В​ы​ ​у​с​п​е​ш​н​о​ ​з​а​р​е​г​и​с​т​р​и​р​о​в​а​л​и​с​ь
	 */
	registeredSuccessfully: string
	/**
	 * Р​е​г​и​с​т​р​а​ц​и​я
	 */
	registration: string
	/**
	 * Д​а​т​а​ ​р​е​г​и​с​т​р​а​ц​и​и
	 */
	registrationDate: string
	/**
	 * У​д​а​л​и​т​ь
	 */
	remove: string
	/**
	 * У​д​а​л​и​т​ь​ ​а​в​а​т​а​р
	 */
	removeAvatar: string
	/**
	 * У​д​а​л​и​т​ь​ ​а​к​к​а​у​н​т
	 */
	removeUser: string
	/**
	 * С​б​р​о​с​и​т​ь
	 */
	reset: string
	/**
	 * С​с​ы​л​к​а​ ​н​а​ ​с​б​р​о​с​ ​б​ы​л​а​ ​о​т​п​р​а​в​л​е​н​а​ ​н​а​ ​в​а​ш​ ​а​д​р​е​с​ ​э​л​е​к​т​р​о​н​н​о​й​ ​п​о​ч​т​ы
	 */
	resetLinkSent: string
	/**
	 * Р​о​л​ь
	 */
	role: string
	/**
	 * Н​а​з​н​а​ч​е​н​и​е​ ​р​о​л​и
	 */
	roleAssigning: string
	/**
	 * Р​о​л​ь​ ​у​с​п​е​ш​н​о​ ​с​о​з​д​а​н​а
	 */
	roleCreatedSuccessfully: string
	/**
	 * С​о​з​д​а​н​и​е​ ​р​о​л​и
	 */
	roleCreating: string
	/**
	 * Р​о​л​ь​ ​у​с​п​е​ш​н​о​ ​о​т​р​е​д​а​к​т​и​р​о​в​а​н​а
	 */
	roleEditedSuccessfully: string
	/**
	 * Р​е​д​а​к​т​и​р​о​в​а​н​и​е​ ​р​о​л​и
	 */
	roleEditing: string
	/**
	 * Р​о​л​ь​ ​у​с​п​е​ш​н​о​ ​у​д​а​л​е​н​а
	 */
	roleRemovedSuccessfully: string
	/**
	 * У​д​а​л​е​н​и​е​ ​р​о​л​и
	 */
	roleRemoving: string
	/**
	 * В​ы​ ​у​в​е​р​е​н​ы​,​ ​ч​т​о​ ​х​о​т​и​т​е​ ​у​д​а​л​и​т​ь​ ​р​о​л​ь​ ​<​b​>​{​{​r​o​l​e​}​}​<​/​b​>​?
	 */
	roleRemovingQuestion: string
	/**
	 * Р​о​л​и
	 */
	roles: string
	/**
	 * С​о​х​р​а​н​и​т​ь
	 */
	save: string
	/**
	 * П​о​и​с​к
	 */
	search: string
	/**
	 * О​т​п​р​а​в​и​т​ь
	 */
	send: string
	/**
	 * О​т​п​р​а​в​и​т​ь​ ​с​с​ы​л​к​у​ ​н​а​ ​с​б​р​о​с
	 */
	sendResetLink: string
	/**
	 * П​р​о​с​т​о​й​ ​л​э​й​а​у​т
	 */
	simpleLayout: string
	/**
	 * С​о​р​т​и​р​о​в​к​а
	 */
	sorting: string
	/**
	 * У​с​п​е​х
	 */
	success: string
	/**
	 * З​а​г​о​л​о​в​о​к
	 */
	title: string
	/**
	 * З​а​г​о​л​о​в​о​к​ ​(​А​-​Я​)
	 */
	titleAsc: string
	/**
	 * З​а​г​о​л​о​в​о​к​ ​(​Я​-​А​)
	 */
	titleDesc: string
	/**
	 * Р​а​з​б​а​н​и​т​ь
	 */
	unban: string
	/**
	 * З​а​г​р​у​з​и​т​ь​ ​а​в​а​т​а​р
	 */
	uploadAvatar: string
	/**
	 * П​о​л​ь​з​о​в​а​т​е​л​ь
	 */
	user: string
	/**
	 * П​о​л​ь​з​о​в​а​т​е​л​ь​ ​у​с​п​е​ш​н​о​ ​з​а​б​а​н​е​н
	 */
	userBannedSuccessfully: string
	/**
	 * Б​а​н​ ​п​о​л​ь​з​о​в​а​т​е​л​я
	 */
	userBanning: string
	/**
	 * И​м​я​ ​п​о​л​ь​з​о​в​а​т​е​л​я
	 */
	username: string
	/**
	 * А​к​к​а​у​н​т​ ​у​с​п​е​ш​н​о​ ​у​д​а​л​ё​н
	 */
	userRemovedSuccessfully: string
	/**
	 * У​д​а​л​е​н​и​е​ ​а​к​к​а​у​н​т​а
	 */
	userRemoving: string
	/**
	 * Д​л​я​ ​п​о​д​т​в​е​р​ж​д​е​н​и​я​ ​н​а​п​и​ш​и​т​е​ ​в​а​ш​е​ ​и​м​я​ ​п​о​л​ь​з​о​в​а​т​е​л​я​.
	 */
	userRemovingConfirmation: string
	/**
	 * В​ы​ ​д​е​й​с​т​в​и​т​е​л​ь​н​о​ ​х​о​т​и​т​е​ ​у​д​а​л​и​т​ь​ ​э​т​о​т​ ​а​к​к​а​у​н​т​ ​б​е​з​ ​в​о​з​м​о​ж​н​о​с​т​и​ ​в​о​с​с​т​а​н​о​в​л​е​н​и​я​?
	 */
	userRemovingQuestion: string
	/**
	 * П​о​л​ь​з​о​в​а​т​е​л​и
	 */
	users: string
	/**
	 * П​о​л​ь​з​о​в​а​т​е​л​ь​ ​у​с​п​е​ш​н​о​ ​р​а​з​б​а​н​е​н
	 */
	userUnbannedSuccessfully: string
	/**
	 * П​р​е​д​у​п​р​е​ж​д​е​н​и​е
	 */
	warning: string
	/**
	 * К​т​о
	 */
	who: string
	/**
	 * Д​а
	 */
	yes: string
}

export type TranslationFunctions = {
	/**
	 * Действия
	 */
	actions: () => LocalizedString
	/**
	 * Добавить
	 */
	add: () => LocalizedString
	/**
	 * Назначить роль
	 */
	assignRole: () => LocalizedString
	/**
	 * Автор
	 */
	author: () => LocalizedString
	/**
	 * Аватар
	 */
	avatar: () => LocalizedString
	/**
	 * Аватар успешно удалён
	 */
	avatarRemovedSuccessfully: () => LocalizedString
	/**
	 * Удаление аватара
	 */
	avatarRemoving: () => LocalizedString
	/**
	 * Вы действительно хотите удалить ваш аватар?
	 */
	avatarRemovingQuestion: () => LocalizedString
	/**
	 * Аватар успешно обновлён
	 */
	avatarUpdatedSuccessfully: () => LocalizedString
	/**
	 * Забанить
	 */
	ban: () => LocalizedString
	/**
	 * Автор бана
	 */
	banAuthor: () => LocalizedString
	/**
	 * Дата бана
	 */
	banDate: () => LocalizedString
	/**
	 * Забанен
	 */
	banned: () => LocalizedString
	/**
	 * Причина бана
	 */
	banReason: () => LocalizedString
	/**
	 * Отмена
	 */
	cancel: () => LocalizedString
	/**
	 * Изменить
	 */
	change: () => LocalizedString
	/**
	 * Изменить электронную почту
	 */
	changeEmail: () => LocalizedString
	/**
	 * Изменить пароль
	 */
	changePassword: () => LocalizedString
	/**
	 * Чат
	 */
	chat: () => LocalizedString
	/**
	 * Клики
	 */
	clicks: () => LocalizedString
	/**
	 * Письмо с подтверждением было отправлено на ваш адрес электронной почты
	 */
	confirmationEmailSent: () => LocalizedString
	/**
	 * Подтверждённая электронная почта
	 */
	confirmedEmail: () => LocalizedString
	/**
	 * Содержание
	 */
	content: () => LocalizedString
	/**
	 * Количество
	 */
	count: () => LocalizedString
	/**
	 * Создать
	 */
	create: () => LocalizedString
	/**
	 * Создан
	 */
	created: () => LocalizedString
	/**
	 * Создать новый пост
	 */
	createPost: () => LocalizedString
	/**
	 * Создать роль
	 */
	createRole: () => LocalizedString
	/**
	 * Дата создания (Сначала старые)
	 */
	creationDateAsc: () => LocalizedString
	/**
	 * Дата создания (Сначала новые)
	 */
	creationDateDesc: () => LocalizedString
	/**
	 * Удалено
	 */
	deleted: () => LocalizedString
	/**
	 * Войти
	 */
	doLogin: () => LocalizedString
	/**
	 * Редактировать
	 */
	edit: () => LocalizedString
	/**
	 * Отредактирован
	 */
	edited: () => LocalizedString
	/**
	 * Электронная почта
	 */
	email: () => LocalizedString
	/**
	 * Подтверждение смены электронной почты
	 */
	emailChangeConfirmation: () => LocalizedString
	/**
	 * Письмо с подтверждением было отправлено на ваш новый адрес электронной почты
	 */
	emailChangeConfirmationSent: () => LocalizedString
	/**
	 * Электронная почта успешно изменена
	 */
	emailChangedSuccessfully: () => LocalizedString
	/**
	 * Изменение электронной почты
	 */
	emailChanging: () => LocalizedString
	/**
	 * пусто
	 */
	empty: () => LocalizedString
	/**
	 * Введите содержание...
	 */
	enterContent: () => LocalizedString
	/**
	 * Введите электронную почту...
	 */
	enterEmail: () => LocalizedString
	/**
	 * Введите новый пароль...
	 */
	enterNewPassword: () => LocalizedString
	/**
	 * Введите новый пароль снова...
	 */
	enterNewPasswordAgain: () => LocalizedString
	/**
	 * Введите причину...
	 */
	enterReason: () => LocalizedString
	/**
	 * Введите заголовок...
	 */
	enterTitle: () => LocalizedString
	/**
	 * Ошибка
	 */
	error: () => LocalizedString
	/**
	 * Произошла ошибка
	 */
	errorOccurred: () => LocalizedString
	/**
	 * Забыли пароль?
	 */
	forgotPassword: () => LocalizedString
	/**
	 * На главную
	 */
	goHome: () => LocalizedString
	/**
	 * Главная
	 */
	home: () => LocalizedString
	/**
	 * Информация
	 */
	info: () => LocalizedString
	/**
	 * Вы успешно вошли
	 */
	loggedInSuccessfully: () => LocalizedString
	/**
	 * Вы успешно вышли
	 */
	loggedOutSuccessfully: () => LocalizedString
	/**
	 * Вход
	 */
	login: () => LocalizedString
	/**
	 * Выйти
	 */
	logout: () => LocalizedString
	/**
	 * Сообщение
	 */
	message: () => LocalizedString
	/**
	 * Название
	 */
	name: () => LocalizedString
	/**
	 * Новый пароль
	 */
	newPassword: () => LocalizedString
	/**
	 * Подтверждение нового пароля
	 */
	newPasswordConfirmation: () => LocalizedString
	/**
	 * Нет
	 */
	no: () => LocalizedString
	/**
	 * Старый пароль
	 */
	oldPassword: () => LocalizedString
	/**
	 * Открыть
	 */
	open: () => LocalizedString
	/**
	 * или войти с помощью
	 */
	orLoginWith: () => LocalizedString
	/**
	 * или зарегистрироваться с помощью
	 */
	orRegisterWith: () => LocalizedString
	/**
	 * Пароль
	 */
	password: () => LocalizedString
	/**
	 * Пароль успешно изменён
	 */
	passwordChangedSuccessfully: () => LocalizedString
	/**
	 * Изменение пароля
	 */
	passwordChanging: () => LocalizedString
	/**
	 * Подтверждение пароля
	 */
	passwordConfirmation: () => LocalizedString
	/**
	 * Сброс пароля
	 */
	passwordReset: () => LocalizedString
	/**
	 * Пароль успешно сброшен
	 */
	passwordResetSuccessfully: () => LocalizedString
	/**
	 * Разрешение
	 */
	permission: () => LocalizedString
	/**
	 * Разрешения
	 */
	permissions: () => LocalizedString
	/**
	 * Пост успешно создан
	 */
	postCreatedSuccessfully: () => LocalizedString
	/**
	 * Создание поста
	 */
	postCreating: () => LocalizedString
	/**
	 * Пост успешно отредактирован
	 */
	postEditedSuccessfully: () => LocalizedString
	/**
	 * Редактирование поста
	 */
	postEditing: () => LocalizedString
	/**
	 * Пост успешно удалён
	 */
	postRemovedSuccessfully: () => LocalizedString
	/**
	 * Удаление поста
	 */
	postRemoving: () => LocalizedString
	/**
	 * Вы уверены, что хотите удалить этот пост?
	 */
	postRemovingQuestion: () => LocalizedString
	/**
	 * Посты
	 */
	posts: () => LocalizedString
	/**
	 * Профиль
	 */
	profile: () => LocalizedString
	/**
	 * Профиль успешно изменён
	 */
	profileEditedSuccessfully: () => LocalizedString
	/**
	 * Изменение профиля
	 */
	profileEditing: () => LocalizedString
	/**
	 * Случайное число
	 */
	randomNumber: () => LocalizedString
	/**
	 * Причина
	 */
	reason: () => LocalizedString
	/**
	 * Перенаправляем...
	 */
	redirecting: () => LocalizedString
	/**
	 * Зарегистрироваться
	 */
	register: () => LocalizedString
	/**
	 * Вы успешно зарегистрировались
	 */
	registeredSuccessfully: () => LocalizedString
	/**
	 * Регистрация
	 */
	registration: () => LocalizedString
	/**
	 * Дата регистрации
	 */
	registrationDate: () => LocalizedString
	/**
	 * Удалить
	 */
	remove: () => LocalizedString
	/**
	 * Удалить аватар
	 */
	removeAvatar: () => LocalizedString
	/**
	 * Удалить аккаунт
	 */
	removeUser: () => LocalizedString
	/**
	 * Сбросить
	 */
	reset: () => LocalizedString
	/**
	 * Ссылка на сброс была отправлена на ваш адрес электронной почты
	 */
	resetLinkSent: () => LocalizedString
	/**
	 * Роль
	 */
	role: () => LocalizedString
	/**
	 * Назначение роли
	 */
	roleAssigning: () => LocalizedString
	/**
	 * Роль успешно создана
	 */
	roleCreatedSuccessfully: () => LocalizedString
	/**
	 * Создание роли
	 */
	roleCreating: () => LocalizedString
	/**
	 * Роль успешно отредактирована
	 */
	roleEditedSuccessfully: () => LocalizedString
	/**
	 * Редактирование роли
	 */
	roleEditing: () => LocalizedString
	/**
	 * Роль успешно удалена
	 */
	roleRemovedSuccessfully: () => LocalizedString
	/**
	 * Удаление роли
	 */
	roleRemoving: () => LocalizedString
	/**
	 * Вы уверены, что хотите удалить роль <b>{{role}}</b>?
	 */
	roleRemovingQuestion: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Роли
	 */
	roles: () => LocalizedString
	/**
	 * Сохранить
	 */
	save: () => LocalizedString
	/**
	 * Поиск
	 */
	search: () => LocalizedString
	/**
	 * Отправить
	 */
	send: () => LocalizedString
	/**
	 * Отправить ссылку на сброс
	 */
	sendResetLink: () => LocalizedString
	/**
	 * Простой лэйаут
	 */
	simpleLayout: () => LocalizedString
	/**
	 * Сортировка
	 */
	sorting: () => LocalizedString
	/**
	 * Успех
	 */
	success: () => LocalizedString
	/**
	 * Заголовок
	 */
	title: () => LocalizedString
	/**
	 * Заголовок (А-Я)
	 */
	titleAsc: () => LocalizedString
	/**
	 * Заголовок (Я-А)
	 */
	titleDesc: () => LocalizedString
	/**
	 * Разбанить
	 */
	unban: () => LocalizedString
	/**
	 * Загрузить аватар
	 */
	uploadAvatar: () => LocalizedString
	/**
	 * Пользователь
	 */
	user: () => LocalizedString
	/**
	 * Пользователь успешно забанен
	 */
	userBannedSuccessfully: () => LocalizedString
	/**
	 * Бан пользователя
	 */
	userBanning: () => LocalizedString
	/**
	 * Имя пользователя
	 */
	username: () => LocalizedString
	/**
	 * Аккаунт успешно удалён
	 */
	userRemovedSuccessfully: () => LocalizedString
	/**
	 * Удаление аккаунта
	 */
	userRemoving: () => LocalizedString
	/**
	 * Для подтверждения напишите ваше имя пользователя.
	 */
	userRemovingConfirmation: () => LocalizedString
	/**
	 * Вы действительно хотите удалить этот аккаунт без возможности восстановления?
	 */
	userRemovingQuestion: () => LocalizedString
	/**
	 * Пользователи
	 */
	users: () => LocalizedString
	/**
	 * Пользователь успешно разбанен
	 */
	userUnbannedSuccessfully: () => LocalizedString
	/**
	 * Предупреждение
	 */
	warning: () => LocalizedString
	/**
	 * Кто
	 */
	who: () => LocalizedString
	/**
	 * Да
	 */
	yes: () => LocalizedString
}

export type Formatters = {}
