name: Check

on: [push, workflow_dispatch]

env:
    POSTGRES_URL: postgresql://user:password@postgres:6703/db
    PUBLIC_BASE_URL: http://localhost:6700
    PUBLIC_TITLE: SvelteKit Website Starter

jobs:
    check:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 10.32.1
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24.14.0
                  cache: pnpm
            - name: Install dependencies
              run: pnpm i
            - name: Build
              run: pnpm build
            - name: Validate
              run: pnpm validate
